import type { NextPage } from "next";
import Head from "next/head";
import Banner from "../components/Banner";
import CategoryPicker from "../components/CategoryPicker";
import FeaturedBlogs from "../components/FeaturedBlogs";
import FeaturedProducts from "../components/FeaturedProducts";

interface BannerStaticProps {
  dataBanner: {
    preTitle: string;
    title: string;
  };
  featProductsData: FeatProdCards[];

  blogsData: BlogsCardProps[];
}

export interface FeatProdCards {
  id: string;
  price: string;
  title: string;
  gender: string;
  img: string;
  description: string;
}
export interface BlogsCardProps {
  id: string;
  author: string;
  date: string;
  category: string;
  excerpt: string;
  img: string;
  title: string;
  first_content: string;
  second_content: string;
}

const Home: NextPage<BannerStaticProps> = ({
  dataBanner,
  featProductsData,
  blogsData,
}) => {
  return (
    <>
      <Head>
        <title>Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner preTitle={dataBanner.preTitle} title={dataBanner.title} />

      <CategoryPicker />

      <FeaturedProducts arrCards={featProductsData} />

      <FeaturedBlogs arrBlog={blogsData} />
    </>
  );
};

export async function getStaticProps() {
  const response = await fetch("http://localhost:5001/banner_content");
  const dataBanner = await response.json();

  const responseFeat = await fetch("http://localhost:5001/products/?_limit=4");
  const featProductsData = await responseFeat.json();

  const responseBlog = await fetch("http://localhost:5001/blogs/?_limit=3");
  const blogsData = await responseBlog.json();
  return {
    props: {
      dataBanner,
      featProductsData,
      blogsData,
    },
  };
}

export default Home;
